name: 🚀 Uruchom Generator (Menu)

on:
  workflow_dispatch:
    inputs:
      namespace:
        description: '1. Podaj NAMESPACE dla modeli (np. gui, custom)'
        required: true
        default: 'gui'
      nazwa_paczki:
        description: '2. Podaj NAZWĘ dla paczki zasobów'
        required: true
        default: 'Custom Items Pack'
      opis_paczki:
        description: '3. Podaj OPIS dla paczki'
        required: true
        default: 'Wygenerowane przez GitHub Actions'
      przedmiot_bazowy:
        description: '4. Wybierz przedmiot bazowy z Javy (Vanilla)'
        required: true
        default: 'red_dye'
        type: choice
        options:
          - red_dye
          - grey_stained_glass
          - iron_nugget
          - paper
      typ_przedmiotu:
        description: '5. Wybierz typ przedmiotów w tej sesji'
        required: true
        default: '1'
        type: choice
        options:
          - '1' # Płaski przedmiot (2D)
          - '2' # Model przestrzenny (3D z LOD)
      dystans_lod:
        description: '6. Dystans optymalizacji LOD dla trybu 3D (w blokach)'
        required: true
        default: '32'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie kodu i plików graficznych z repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Uruchomienie skryptu Pythona na plikach lokalnych z repozytorium
        run: |
          python main.py \
            --namespace "${{ github.event.inputs.namespace }}" \
            --packname "${{ github.event.inputs.nazwa_paczki }}" \
            --description "${{ github.event.inputs.opis_paczki }}" \
            --base "${{ github.event.inputs.przedmiot_bazowy }}" \
            --type "${{ github.event.inputs.typ_przedmiotu }}" \
            --lod "${{ github.event.inputs.dystans_lod }}"

      # 🟢 AUTOMATYCZNY ZAPIS FOLDERU GEN DIRECTLY DO PROJEKTU NA GITHUBIE
      - name: Automatyczny zapis folderu GEN do projektu (Commit & Push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add GEN/
          git commit -m "🚀 Wygenerowano nowy pakiet struktur w folderze GEN" || echo "Brak zmian do zapisu"
          git push
