name: 🚀 Uruchom Generator (Menu Catbox)

on:
  workflow_dispatch:
    inputs:
      catbox_url:
        description: '1. Wklej LINK do swojego albumu Catbox (np. https://catbox.moe)'
        required: true
      namespace:
        description: '2. Podaj NAMESPACE dla modeli (np. gui, custom)'
        required: true
        default: 'gui'
      nazwa_paczki:
        description: '3. Podaj NAZWĘ dla paczki zasobów'
        required: true
        default: 'Custom Items Pack'
      opis_paczki:
        description: '4. Podaj OPIS dla paczki'
        required: true
        default: 'Wygenerowane przez Catbox Multi-Add'
      przedmiot_bazowy:
        description: '5. Wybierz przedmiot bazowy z Javy (Vanilla)'
        required: true
        default: 'red_dye'
        type: choice
        options:
          - red_dye
          - grey_stained_glass
          - iron_nugget
          - paper

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie kodu z repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Uruchomienie stabilnego silnika kompilacji Catbox
        run: |
          python main.py \
            --namespace "${{ github.event.inputs.namespace }}" \
            --packname "${{ github.event.inputs.nazwa_paczki }}" \
            --description "${{ github.event.inputs.opis_paczki }}" \
            --base "${{ github.event.inputs.przedmiot_bazowy }}" \
            --catbox_url "${{ github.event.inputs.catbox_url }}"

      - name: Automatyczny zapis folderu GEN do projektu (Commit & Push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add GEN/ || echo "Brak folderu"
          git commit -m "🚀 Wygenerowano masowy pakiet struktur w folderze GEN" || echo "Brak zmian"
          git push origin main
