name: 🚀 Uruchom Zaawansowany Generator (Wbudowane PNG)

on:
  workflow_dispatch:
    inputs:
      pliki_nazwy:
        description: '1. Podaj NAZWY dla przedmiotów oddzielone przecinkami (np. miecz, tarcza, helms)'
        required: true
        default: 'miecz, tarcza'
      pliki_tekstury:
        description: '2. Wklej KODY TEKSTUR Base64 oddzielone przecinkami (w tej samej kolejności co nazwy!)'
        required: true
      namespace:
        description: '3. Podaj NAMESPACE dla modeli'
        required: true
        default: 'gui'
      nazwa_paczki:
        description: '4. Podaj NAZWĘ dla paczki zasobów'
        required: true
        default: 'Custom Items Pack'
      opis_paczki:
        description: '5. Podaj OPIS dla paczki (mcmeta / manifest)'
        required: true
        default: 'Wygenerowane automatycznie przez Generator'
      przedmiot_bazowy:
        description: '6. Wybierz przedmiot bazowy z Javy (Vanilla)'
        required: true
        default: 'red_dye'
        type: choice
        options:
          - red_dye
          - grey_stained_glass
          - iron_nugget
          - paper

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pobieranie kodu z repozytorium
        uses: actions/checkout@v4

      - name: Instalacja Pythona
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Uruchomienie Silnika Dekodowania i Kompilacji Paczek
        run: |
          python main.py \
            --namespace "${{ github.event.inputs.namespace }}" \
            --packname "${{ github.event.inputs.nazwa_paczki }}" \
            --description "${{ github.event.inputs.opis_paczki }}" \
            --base "${{ github.event.inputs.przedmiot_bazowy }}" \
            --pliki_nazwy "${{ github.event.inputs.pliki_nazwy }}" \
            --pliki_tekstury "${{ github.event.inputs.pliki_tekstury }}"

      - name: Automatyczny zapis folderu GEN do projektu (Commit & Push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@://github.com"
          git add GEN/ || echo "Brak folderu GEN"
          git commit -m "🚀 Wygenerowano masowy pakiet struktur w folderze GEN" || echo "Brak zmian"
          git push origin main
